apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nix-cache
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/applications/nix-cache"
  prune: true
  wait: true
  dependsOn:
    - name: storage # Proxmox CSI
      namespace: flux-system
    - name: core # sealed-secrets
      namespace: flux-system
    - name: ingress-nginx
      namespace: flux-system
    - name: cert-manager
      namespace: flux-system
    - name: external-dns
      namespace: flux-system
