---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: attic-chart
  namespace: nix-cache
spec:
  interval: 24h
  url: https://github.com/agentydragon/cluster
  ref:
    branch: main
