apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/k8s/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  dependsOn:
    - name: vault
      namespace: flux-system
    - name: external-secrets-config
      namespace: flux-system
    - name: sso-secrets # Wait for API token generation in Vault
      namespace: flux-system
    - name: cert-manager # Wait for cert-manager for TLS certificates
      namespace: flux-system
    - name: ingress-nginx # Wait for ingress controller for external access
      namespace: flux-system
