apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - authentik-host-configmap.yaml
  - bootstrap-external-secret.yaml
  - secret-key-external-secret.yaml
  - admin-password-external-secret.yaml
  - token-secret.yaml
  - postgres-external-secret.yaml
