---
# Add Let's Encrypt staging CA to cluster trust bundle for staging environment
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cluster-internal-ca-bundle
spec:
  sources:
    - secret:
        name: cluster-root-ca-secret
        key: ca.crt
    - secret:
        name: letsencrypt-staging-root-ca
        key: ca.crt
