apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-ingress
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/vault-ingress"
  prune: true
  wait: true
  dependsOn:
    - name: vault # Core Vault must be ready first
    - name: ingress-nginx
    - name: cert-manager-environment
