apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/k8s/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  dependsOn:
    - name: cert-manager # ESO needs cert-manager for webhook certificates
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: sealedsecrets.bitnami.com
      namespace: ""
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: terraforms.infra.contrib.fluxcd.io
      namespace: ""
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: externalsecrets.external-secrets.io
      namespace: ""
    - apiVersion: apps/v1
      kind: Deployment
      name: sealed-secrets-controller
      namespace: kube-system
