apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-app
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/applications/test-app"
  prune: true
  wait: true
  dependsOn:
    - name: ingress-nginx # test-app has ingress.yaml requiring ingress controller
    # platform dependency removed - test-app only needs ingress-nginx which is already specified
