apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-blueprint-matrix-secret
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/authentik-blueprint/matrix-secret"
  prune: true
  wait: true
  dependsOn:
    - name: matrix # Wait for Matrix namespace to be created
      namespace: flux-system
    - name: authentik-blueprint-matrix-provider # Wait for provider to be created
      namespace: flux-system
