apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-environment
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/cert-manager-environment/overlays/staging"
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager # Wait for cert-manager CRDs (ClusterIssuer)
      namespace: flux-system
    - name: cert-manager-trust # Wait for trust-manager CRDs (Bundle)
      namespace: flux-system
  # Verify ClusterIssuer is created
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: letsencrypt-prod
      namespace: ""
