apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-blueprint-gitea-secret
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/authentik-blueprint/gitea-secret"
  prune: true
  wait: true
  dependsOn:
    - name: authentik-blueprint-gitea-provider # Wait for provider to be created
      namespace: flux-system
    - name: external-secrets-config # Ensure ClusterSecretStore exists
      namespace: flux-system
