apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-blueprint-users
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/authentik-blueprint/users"
  prune: true
  wait: true
  dependsOn:
    - name: core # Wait for tofu-controller to install Terraform CRD
      namespace: flux-system
    - name: authentik # Wait for authentik to be ready
      namespace: flux-system
    - name: external-secrets-config # Wait for ESO to be configured
      namespace: flux-system
