---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-proxy-cache
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/k8s/harbor-proxy-cache
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  dependsOn:
    - name: core # Wait for tofu-controller to install Terraform CRD
    - name: harbor # Wait for Harbor to be deployed
