apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-blueprint-grafana-secret
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/k8s/authentik-blueprint/grafana-secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: monitoring-namespace
      namespace: flux-system
    - name: external-secrets-config
      namespace: flux-system
    - name: authentik-blueprint-grafana-provider
      namespace: flux-system
