apiVersion: v1
kind: Namespace
metadata:
  name: dns-system
  labels:
    name: dns-system
    # Allow unsafe sysctls (net.ipv4.tcp_mtu_probing) for PMTUD blackhole mitigation
    pod-security.kubernetes.io/enforce: privileged
