apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devbot
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/k8s/agents/devbot
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-config
    - name: storage # PVCs require storage
