apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-token
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/vault-token"
  prune: true
  wait: true
  dependsOn:
    - name: vault # Wait for Vault instance to be ready
    - name: external-secrets-config # Required for ExternalSecret resources
