apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/k8s/external-secrets-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
  dependsOn:
    - name: vault
      namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets
      namespace: external-secrets-system
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets-webhook
      namespace: external-secrets-system
