---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: powerdns-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/k8s/powerdns-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: powerdns
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: powerdns-operator
      namespace: powerdns-operator
  timeout: 5m
