---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: powerdns-operator
  namespace: powerdns-operator
spec:
  interval: 24h
  url: https://powerdns-operator.github.io/PowerDNS-Operator-helm-chart
