apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-blueprint-kagent
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/k8s/authentik-blueprint/kagent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: core # Wait for tofu-controller to install Terraform CRD
    - name: sso-secrets
    - name: authentik-blueprint-users
