apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kagent

resources:
  - namespace.yaml
  - gitrepository.yaml
  - anthropic-secret.yaml
  - crds-helmrelease.yaml
  - helmrelease.yaml
  - authentik-proxy-service.yaml
  - ingress.yaml
