apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-blueprint-harbor-secret
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cluster/k8s/authentik-blueprint/harbor-secret"
  prune: true
  wait: true
  dependsOn:
    - name: harbor # Wait for Harbor namespace and app
      namespace: flux-system
    - name: authentik-blueprint-harbor-provider # Wait for provider to be created
      namespace: flux-system
