apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/k8s/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
  dependsOn:
    - name: external-secrets-operator
      namespace: flux-system
    - name: vault
      namespace: flux-system
