apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/k8s/monitoring-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
  timeout: 10m
  dependsOn:
    - name: monitoring-namespace
    - name: ingress-nginx
    - name: cert-manager-environment
    - name: external-secrets-config
    - name: authentik-blueprint-grafana-secret
